"use client";

import type { LearningInsight } from "@nexus/shared";

export type InsightState =
  | { status: "idle" }
  | { status: "loading" }
  | ({ status: "ready" } & LearningInsight)
  | { status: "error" };

const CONFIDENCE_LABEL: Record<LearningInsight["confidence"], string> = {
  high: "High confidence",
  medium: "Medium confidence",
  low: "Low confidence",
};

export default function AIInsightCard({ state }: { state: InsightState }) {
  if (state.status === "idle") {
    return (
      <div className="rounded-2xl border border-dashed border-border bg-white/60 p-6 text-center text-sm text-ink-muted">
        Complete a challenge in the game to see your first NEXUS learning
        insight here.
      </div>
    );
  }

  if (state.status === "loading") {
    return (
      <div className="rounded-2xl border border-border bg-white p-6 shadow-sm">
        <CardHeader />
        <p className="mt-3 text-sm text-ink-muted">
          Generating learning insight
          <span className="inline-block animate-pulse">…</span>
        </p>
      </div>
    );
  }

  if (state.status === "error") {
    return (
      <div className="rounded-2xl border border-border bg-white p-6 shadow-sm">
        <CardHeader />
        <p className="mt-3 text-sm text-ink-muted">
          Couldn&apos;t reach the insight service this time. Keep playing —
          your mastery has already been updated in-game.
        </p>
      </div>
    );
  }

  return (
    <div
      className="relative overflow-hidden rounded-2xl border border-transparent bg-white p-6 shadow-md"
      style={{ animation: "insightAppear 0.35s ease-out" }}
    >
      <div className="gradient-purple-blue absolute inset-x-0 top-0 h-1" />
      <div className="flex items-center justify-between">
        <CardHeader />
        <span className="rounded-full bg-surface-lavender px-2.5 py-1 text-[10px] font-bold text-purple-dark uppercase">
          {CONFIDENCE_LABEL[state.confidence]}
        </span>
      </div>
      <h3 className="mt-3 font-display text-lg font-bold text-ink">
        {state.headline}
      </h3>
      <p className="mt-2 text-sm text-ink-muted">{state.explanation}</p>
      <p className="mt-3 flex items-start gap-1.5 text-sm font-semibold text-purple">
        <span aria-hidden="true">→</span> {state.suggestion}
      </p>
      {state.source === "fallback" && (
        <p className="mt-4 text-[11px] font-medium text-ink-muted/70">
          Generated by NEXUS&apos;s built-in insight logic.
        </p>
      )}
    </div>
  );
}

function CardHeader() {
  return (
    <div className="flex items-center gap-2">
      <span className="gradient-purple-blue flex h-6 w-6 items-center justify-center rounded-full text-xs text-white">
        ✦
      </span>
      <span className="text-xs font-bold tracking-[0.15em] text-purple uppercase">
        Nexus Learning Insight
      </span>
    </div>
  );
}
